# Core Colors
background            #17130b
foreground            #eae1d4
selection_foreground  #e6c26c
selection_background  #3e2e00
cursor                #e6c26c
cursor_text_color     #17130b

# Regular Colors
color0  #17130b
color1  #ffb4ab
color2  #e6c26c
color3  #afcfab
color4  #ffdf96
color5  #f3e1bb
color6  #d6c5a0
color7  #eae1d4

# Bright Colors
color8  #3d392f
color9  #ffb4ab
color10 #e6c26c
color11 #afcfab
color12 #ffdf96
color13 #f3e1bb 
color14 #d6c5a0
color15 #eae1d4
