# --- Fonte ---
# O nome exato da Nerd Font instalada
font_family      GohuFont Nerd Font
font_size        11.0
bold_font        auto
italic_font      auto

# --- Cores de Pergaminho (Baseado no Solarized Light) ---
background            #fdf6e3
foreground            #586e75
cursor                #93a1a1
selection_background  #eee8d5
selection_foreground  #586e75

# --- Estilo da Janela ---
# Isso dá o respiro nas bordas para parecer papel
window_padding_width  15

# Opacidade leve para ver o wallpaper do Hyprland no fundo
background_opacity    0.95

# --- Performance ---
repaint_delay    10
input_delay      3
sync_to_monitor  yes
