# Motor do Wallpaper
exec-once = swww-daemon &

# Barra de Status (Silenciada)
exec-once = waybar -c ~/.config/waybar/configs/"[TOP] 0-Ja-0 Been modified" -s ~/.config/waybar/style/"bintang default.css" 

# Cores e Estética do Chrono Trigger
exec-once = matugen image ~/Downloads/arch-hyprland/wallpapers/chronothrigger.png &
exec-once = swww img ~/Downloads/arch-hyprland/wallpapers/chronothrigger.png &

# Utilidades de Sistema (Wi-Fi e Bluetooth)
exec-once = nm-applet --indicator
exec-once = blueman-applet

# Layout do Teclado
exec-once = echo "br" > ~/.cache/kb_layout


